export const ADMIN_ROUTE = '/admin'
export const AUTH_ROUTE = '/auth'
export const LOGIN_ROUTE = '/login'
export const HOMEPAGE_ROUTE = '/'
export const COLLECTIONS_ROUTE = '/collections'
export const USER_ROUTE = '/user/:id'
export const REGISTRATION_ROUTE = '/register'
export const COLLECTION_CREATE_ROUTE = COLLECTIONS_ROUTE + "/create";
export const CREATE_ITEM_ROUTE = COLLECTIONS_ROUTE + "/:id/item/create";